### PR TITLE
docker outside of docker (GSI-412)

### PR DESCRIPTION
**Pull request by KerstenBreuer**
Allow testcontainers to be run on the docker host deamon.

This is just a prototype and should be implemented in the template repository.

### CODE REVIEW

**Review by TheByronHimes — APPROVED** [review]
Seems to work fine for me.

**Comment by dontseyit** [comment]
I've tested the branch with the MacOS M2 chip and Docker Desktop v4.23.0, Docker engine v24.0.6. The devcontainer is running without problem and tests are passing.

**Comment by Cito** [comment]
I have now tested this on MacOS 13 with Intel and Orbstack. The two test containers are created, but then the tests are hanging. Need to investigate more.

**Comment by lkuchenb** [comment]
@Cito Works fine for me with Orbstack and arm64, after manually pulling the amd64 version of kafka because testcontainers (and docker pull in general) doesn't automatically fall back to amd64 images if not arm64 images are available. All tests pass.

**Comment by Cito** [comment]
After upgrading from macOS 13 to 14, it now also worked for me, without further ado. (I know you already upgraded.)

**Comment by KerstenBreuer** [comment]
Great, so all problems are resolved now? @Cito Could you leave an approval?

**Comment by KerstenBreuer** [comment]
Requesting approval once this PR is merged: https://github.com/ghga-de/microservice-repository-template/pull/169

**Review by Cito — APPROVED** [review]

**Review by Cito — APPROVED** [review]

**Comment by KerstenBreuer** [comment]
Thanks @Cito, @dontseyit, @TheByronHimes, and @lkuchenb for testing this.

**Pull request merged**
